### ISSUE TITLE
O Script para de funcionar depois de um tempo

### ISSUE THREAD

**Issue by mr-zann** [ThallesLazaro/Fixar-Volume-do-Microfone#1]
Aqui na minha máquina, eu ativo o script e seleciono o volume 90 e sim, ele funciona. Após um tempo usando meet ou WhatsApp Web para mandar áudios, vejo que ele voltar a baixar o volume.
Isso sem reiniciar a máquina.

**Comment by ThallesLazaro** [comment]
> Aqui na minha máquina, eu ativo o script e seleciono o volume 90 e sim, ele funciona. Após um tempo usando meet ou WhatsApp Web para mandar áudios, vejo que ele voltar a baixar o volume. Isso sem reiniciar a máquina.

Oi [ZannF0x](https://github.com/ZannF0x), realmente eu percebi que depois de vários dias usando a ferramenta, ela parava de funcionar depois de um tempo ao executar, fiz algumas modificações no código e agora não diminui mais o volume depois de um tempo, baixa o pacote atualizado, testa e me fala se resolveu por favor, abraços.

**Comment by ZannF0x** [comment]
Usei desde hoje pela manhã e até agora permanece o volume que selecionei, acredito que está concertado.
Valeu! :D
